// SPDX-License-Identifier: AGPL-3.0-only

use std::collections::HashMap;
use std::env;
use std::path::PathBuf;

/// Per-category sampling defaults parsed from MODEL.toml `[sampling.*]`.
#[derive(Debug, Clone)]
struct SamplingCat {
    temperature: f32,
    top_p: f32,
    top_k: u32,
    presence_penalty: f32,
    frequency_penalty: f32,
    repetition_penalty: f32,
    // DRY sampler params (see SamplingCategory in atlas-kernels/src/lib.rs
    // for full rationale). Defaults disable DRY; individual MODEL.toml
    // `[sampling.*]` tables opt in when needed.
    dry_multiplier: f32,
    dry_base: f32,
    dry_allowed_length: u32,
    // LZ penalty (arXiv:2504.20131). Frequency-weighted n-gram penalty
    // over the recent token window. 0.0 = disabled. 0.2 is the SGLang
    // reference value; lossless on AIME/GPQA at that strength.
    lz_penalty: f32,
}

impl Default for SamplingCat {
    fn default() -> Self {
        Self {
            temperature: 0.7,
            top_p: 0.95,
            top_k: 20,
            presence_penalty: 0.0,
            frequency_penalty: 0.0,
            repetition_penalty: 1.0,
            dry_multiplier: 0.0,
            dry_base: 1.75,
            dry_allowed_length: 2,
            lz_penalty: 0.0,
        }
    }
}

/// A `(model_type, optional hidden_size)` pair declaring which models a kernel target supports.
#[derive(Debug, Clone)]
struct ModelTypeMatch {
    model_type: String,
    hidden_size: Option<usize>,
}

/// A resolved (hw, model, quant) compilation target.
struct Target {
    hw: String,
    model: String,
    quant: String,
    arch: String,
    /// Per-model quant dir (for KERNEL.toml and optional override .cu files).
    model_kernel_dir: PathBuf,
    /// Common quant dir (hw_dir/quant/) with shared .cu files.
    common_kernel_dir: Option<PathBuf>,
    extra_flags: Vec<String>,
    module_overrides: HashMap<String, String>,
    sampling_thinking_text: SamplingCat,
    sampling_thinking_coding: SamplingCat,
    sampling_non_thinking: SamplingCat,
    sampling_tools: SamplingCat,
    behavior_thinking_in_tools: bool,
    behavior_max_thinking_budget: u32,
    behavior_thinking_default: bool,
    behavior_fp8_kv_calibration_tokens: usize,
    behavior_default_kv_dtype: String,
    behavior_default_num_drafts: u32,
    behavior_disable_tool_steering: bool,
    behavior_tool_call_parser: String,
    behavior_enable_loop_watchdog: bool,
    // PR #74 added 10 new behavior fields used by build_codegen.rs. Default
    // to safe values (false / 0 / empty) until a model wants to customize.
    behavior_think_loop_min_repeats: u32,
    behavior_think_loop_scan_window: u32,
    behavior_confidence_early_stop: bool,
    behavior_confidence_run_length: u32,
    behavior_fuzzy_repeat_tolerance_div: u32,
    behavior_max_inter_tool_prose: u32,
    behavior_tscg: bool,
    behavior_disable_tool_grammar: bool,
    behavior_rollback_resteer: bool,
    behavior_rom_head: String,
    /// Which `(model_type, hidden_size)` pairs this kernel target supports.
    /// Parsed from `[[model_types]]` in MODEL.toml.
    model_type_matches: Vec<ModelTypeMatch>,
    /// `[dflash]` section if present in MODEL.toml — drafter pairing for
    /// block-diffusion speculative decoding. `None` when the model has no
    /// associated DFlash drafter checkpoint.
    dflash: Option<DflashRaw>,
}

#[derive(Default, Clone)]
struct DflashRaw {
    draft_model: String,
    gamma: usize,
    window_size: usize,
    mask_token_id: u32,
    target_layer_ids: Vec<usize>,
}

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    println!("cargo:rerun-if-env-changed=ATLAS_SKIP_BUILD");
    // Without these the cargo cache short-circuits when only the target
    // selection env vars change, leaving an out-of-date kernel registry
    // baked into the binary (e.g. defaulting to qwen3-next-only after a
    // prior `ATLAS_TARGET_MODEL=*` build).
    println!("cargo:rerun-if-env-changed=ATLAS_TARGET_HW");
    println!("cargo:rerun-if-env-changed=ATLAS_TARGET_MODEL");
    println!("cargo:rerun-if-env-changed=ATLAS_TARGET_QUANT");
    if matches!(
        env::var("ATLAS_SKIP_BUILD").as_deref(),
        Ok("1") | Ok("true")
    ) {
        let stub = "// Auto-generated by build.rs (ATLAS_SKIP_BUILD stub — no nvcc invoked).\n\
            pub fn ptx_modules() -> Vec<(&'static str, &'static str)> { Vec::new() }\n\
            pub fn all_ptx_sets() -> Vec<TargetPtxSet> { Vec::new() }\n";
        std::fs::write(out_dir.join("target_ptx.rs"), stub)
            .expect("write ATLAS_SKIP_BUILD stub target_ptx.rs");
        println!("cargo:rustc-env=ATLAS_PTX_DIR={}", out_dir.display());
        return;
    }

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let workspace_root = manifest_dir.parent().unwrap().parent().unwrap();

    // ── Resolve targets (supports wildcards) ──
    let targets = resolve_targets(workspace_root);

    assert!(
        !targets.is_empty(),
        "No kernel targets resolved. Check ATLAS_TARGET_* env vars."
    );

    // ── Resolve compute target (compiler) from HARDWARE.toml vendor ──
    // This abstraction supports NVIDIA (nvcc→PTX), AMD (hipcc→HSACO),
    // Apple (xcrun→metallib), Intel (icpx→SPIR-V). Only NVIDIA is implemented.
    let hw_dir = workspace_root
        .join("kernels")
        .join(env::var("ATLAS_TARGET_HW").unwrap_or_else(|_| "gb10".into()));
    let hw_toml_path = hw_dir.join("HARDWARE.toml");
    let hw_toml: toml::Value = {
        let content = std::fs::read_to_string(&hw_toml_path)
            .unwrap_or_else(|_| panic!("Cannot read {}", hw_toml_path.display()));
        content
            .parse()
            .unwrap_or_else(|e| panic!("Invalid HARDWARE.toml: {e}"))
    };
    let vendor_str = hw_toml
        .get("hardware")
        .and_then(|h| h.get("vendor"))
        .and_then(|v| v.as_str());
    let compute_target = resolve_compute_target(vendor_str);
    let output_ext = compute_target.output_extension();

    // Per-target: (target_idx, vec of (stem, module_name))
    let mut all_target_modules: Vec<Vec<(String, String)>> = Vec::new();

    for (idx, target) in targets.iter().enumerate() {
        let cu_files = collect_cu_files(
            target.common_kernel_dir.as_deref(),
            &target.model_kernel_dir,
        );
        assert!(
            !cu_files.is_empty(),
            "No .{} files found for target ({}, {}, {})",
            compute_target.source_extension(),
            target.hw,
            target.model,
            target.quant,
        );

        // Compile all kernel source files via the ComputeTarget abstraction.
        // The NvidiaTarget uses nvcc; future targets (AMD, Apple, Intel) would
        // use their respective compilers.
        //
        // PTX-cache freshness check: skip nvcc when an existing PTX is newer
        // than every potentially-relevant source (.cu + every .cuh in the
        // model and common dirs) AND the target-identity signature for this
        // `t{idx}__` slot matches the prior build. The signature guards
        // against the case where ATLAS_TARGET_MODEL changes and re-numbers
        // the targets — without it we'd happily reuse a stale PTX from a
        // different model that happened to land at the same `idx`.
        let signature = format!(
            "{}|{}|{}|{}",
            target.hw,
            target.model,
            target.quant,
            target.arch,
        );
        let signature_file = out_dir.join(format!("t{idx}__signature"));
        let signature_matches = std::fs::read_to_string(&signature_file)
            .map(|s| s == signature)
            .unwrap_or(false);
        if !signature_matches {
            let _ = std::fs::write(&signature_file, &signature);
        }
        let header_floor = target_header_floor(
            &target.model_kernel_dir,
            target.common_kernel_dir.as_deref(),
            &signature_file,
        );

        let mut errors = Vec::new();
        let mut compiled = 0usize;
        let mut cached = 0usize;
        for cu_file in &cu_files {
            let stem = cu_file.file_stem().unwrap().to_str().unwrap().to_string();
            let out_file = out_dir.join(format!("t{idx}__{stem}.{output_ext}"));

            // Per-file freshness: skip nvcc when output exists and is
            // newer than max(this .cu's mtime, target header floor).
            // The header floor folds in every `.cuh` in the model+common
            // dirs plus the signature file mtime, so touching a header
            // invalidates every `.cu` in the target while touching a
            // single `.cu` only invalidates itself. Conservative —
            // false negatives (recompile when unchanged) are a minor
            // perf miss; false positives (skip when changed) would
            // silently ship stale PTX.
            if signature_matches {
                let cu_mt = std::fs::metadata(cu_file)
                    .and_then(|m| m.modified())
                    .ok();
                let out_mt = std::fs::metadata(&out_file)
                    .and_then(|m| m.modified())
                    .ok();
                let src_floor = match (cu_mt, header_floor) {
                    (Some(a), Some(b)) => Some(a.max(b)),
                    (Some(a), None) => Some(a),
                    (None, Some(b)) => Some(b),
                    (None, None) => None,
                };
                if let (Some(out_mt), Some(src_mt)) = (out_mt, src_floor) {
                    if out_mt > src_mt {
                        cached += 1;
                        continue;
                    }
                }
            }

            if let Err(e) =
                compute_target.compile(cu_file, &out_file, &target.arch, &target.extra_flags)
            {
                errors.push(e);
            } else {
                compiled += 1;
            }
        }
        if !errors.is_empty() {
            panic!("Kernel compilation failed:\n{}", errors.join("\n"));
        }
        if cached > 0 {
            println!(
                "cargo:warning=atlas-kernels: target {idx} ({}, {}, {}): {} cached, {} compiled",
                target.hw, target.model, target.quant, cached, compiled
            );
        }

        for cu_file in &cu_files {
            println!("cargo:rerun-if-changed={}", cu_file.display());
        }

        // Collect (stem, module_name) pairs sorted by module_name
        let mut modules: Vec<(String, String)> = cu_files
            .iter()
            .map(|f| {
                let stem = f.file_stem().unwrap().to_str().unwrap().to_string();
                let module_name = target
                    .module_overrides
                    .get(&stem)
                    .cloned()
                    .unwrap_or_else(|| stem.clone());
                (stem, module_name)
            })
            .collect();
        modules.sort_by(|a, b| a.1.cmp(&b.1));

        all_target_modules.push(modules);

        println!(
            "cargo:rerun-if-changed={}",
            target.model_kernel_dir.display()
        );
        if let Some(ref common) = target.common_kernel_dir {
            println!("cargo:rerun-if-changed={}", common.display());
        }
        let n_overrides = find_cu_files(&target.model_kernel_dir).len();
        println!(
            "cargo:warning=atlas-kernels: compiled {} kernels for target {} ({}, {}, {}){}",
            cu_files.len(),
            idx,
            target.hw,
            target.model,
            target.quant,
            if n_overrides > 0 {
                format!(" ({n_overrides} model-specific overrides)")
            } else {
                String::new()
            },
        );
    }

    // ── Generate target_ptx.rs ──
    // PR #74 added output_ext + output_is_text args.
    let output_is_text_val = compute_target.output_is_text();
    let generated = generate_target_ptx_rs(
        &targets,
        &all_target_modules,
        output_ext,
        output_is_text_val,
    );
    let gen_path = out_dir.join("target_ptx.rs");
    std::fs::write(&gen_path, &generated)
        .unwrap_or_else(|e| panic!("Failed to write {}: {e}", gen_path.display()));

    println!("cargo:rustc-env=ATLAS_PTX_DIR={}", out_dir.display());
}

/// Resolve all compilation targets from env vars, expanding wildcards.
fn resolve_targets(workspace_root: &std::path::Path) -> Vec<Target> {
    let hw = env::var("ATLAS_TARGET_HW").unwrap_or_else(|_| "gb10".into());
    let model_spec = env::var("ATLAS_TARGET_MODEL").unwrap_or_else(|_| "qwen3-next-80b-a3b".into());
    let quant_spec = env::var("ATLAS_TARGET_QUANT").unwrap_or_else(|_| "nvfp4".into());

    let hw_dir = workspace_root.join("kernels").join(&hw);
    assert!(
        hw_dir.is_dir(),
        "Hardware kernel directory not found: {}",
        hw_dir.display()
    );

    // Parse HARDWARE.toml (shared across all models for this hw)
    let hw_toml_path = hw_dir.join("HARDWARE.toml");
    let hw_toml: toml::Value = toml::from_str(
        &std::fs::read_to_string(&hw_toml_path)
            .unwrap_or_else(|e| panic!("{}: {e}", hw_toml_path.display())),
    )
    .unwrap_or_else(|e| panic!("Bad TOML in {}: {e}", hw_toml_path.display()));
    let arch = hw_toml["hardware"]["arch"]
        .as_str()
        .expect("hardware.arch must be a string in HARDWARE.toml")
        .to_string();
    println!("cargo:rerun-if-changed={}", hw_toml_path.display());

    // Propagate hardware config flags to Rust code via compile-time env vars
    if let Some(fp32_res) = hw_toml["hardware"]
        .get("use_fp32_residual")
        .and_then(|v| v.as_bool())
    {
        println!(
            "cargo:rustc-env=ATLAS_HW_FP32_RESIDUAL={}",
            if fp32_res { "true" } else { "false" }
        );
    }

    // Expand model wildcard (exclude common quant dirs like nvfp4/)
    let models: Vec<String> = if model_spec == "*" {
        list_subdirs(&hw_dir)
            .into_iter()
            .filter(|d| hw_dir.join(d).join("MODEL.toml").exists())
            .collect()
    } else {
        vec![model_spec]
    };

    let mut targets = Vec::new();
    for model in &models {
        let model_dir = hw_dir.join(model);
        if !model_dir.is_dir() {
            panic!("Model kernel directory not found: {}", model_dir.display());
        }

        // Expand quant wildcard
        let quants: Vec<String> = if quant_spec == "*" {
            list_subdirs(&model_dir)
        } else {
            vec![quant_spec.clone()]
        };

        for quant in &quants {
            let model_kernel_dir = model_dir.join(quant);
            let common_kernel_dir = hw_dir.join(quant);
            // SHARED `common/` dir (upstream PR #74 layout): kernels that
            // apply to any (model, quant) combination. Examples: multi-seq
            // SSM kernels, tree-aware kv scatter, paged_decode kgamma
            // variants. Lives at `kernels/$hw/common/` and is merged into
            // the kernel set alongside the quant-specific common dir below.
            let shared_kernel_dir = hw_dir.join("common");
            let has_shared_dir = shared_kernel_dir.is_dir();

            // At least one of common or model-specific dir must exist
            let has_model_dir = model_kernel_dir.is_dir();
            let has_common_dir = common_kernel_dir.is_dir();
            assert!(
                has_model_dir || has_common_dir || has_shared_dir,
                "No kernel directory found for ({model}, {quant}). \
                 Expected {}, {} or {}.",
                model_kernel_dir.display(),
                common_kernel_dir.display(),
                shared_kernel_dir.display(),
            );

            // KERNEL.toml: prefer model-specific, fall back to common
            let toml_dir = if has_model_dir && model_kernel_dir.join("KERNEL.toml").exists() {
                &model_kernel_dir
            } else if has_common_dir {
                &common_kernel_dir
            } else {
                &model_kernel_dir
            };
            // parse_kernel_toml now takes vendor (PR #74) — hardcoded to nvidia.
            let (extra_flags, module_overrides) = parse_kernel_toml(toml_dir, "nvidia");

            // parse_behavior returns ParsedBehavior struct (was tuple before #74).
            let (s_tt, s_tc, s_nt, s_tools) = parse_sampling_presets(&model_dir);
            let pb = parse_behavior(&model_dir);
            let b_thinking_in_tools = pb.thinking_in_tools;
            let b_max_thinking_budget = pb.max_thinking_budget;
            let b_thinking_default = pb.thinking_default;
            let b_fp8_kv_cal = pb.fp8_kv_calibration_tokens;
            let b_default_kv_dtype = pb.default_kv_dtype.clone();
            let b_default_num_drafts = pb.default_num_drafts;
            let b_disable_tool_steering = pb.disable_tool_steering;
            let b_tool_call_parser = pb.tool_call_parser.clone();
            let b_enable_loop_watchdog = pb.enable_loop_watchdog;
            let model_type_matches = parse_model_types(&model_dir);
            let dflash = parse_dflash(&model_dir);

            targets.push(Target {
                hw: hw.clone(),
                model: model.clone(),
                quant: quant.clone(),
                arch: arch.clone(),
                model_kernel_dir,
                common_kernel_dir: if has_common_dir {
                    Some(common_kernel_dir)
                } else {
                    None
                },
                extra_flags,
                module_overrides,
                sampling_thinking_text: s_tt,
                sampling_thinking_coding: s_tc,
                sampling_non_thinking: s_nt,
                sampling_tools: s_tools,
                behavior_thinking_in_tools: b_thinking_in_tools,
                behavior_max_thinking_budget: b_max_thinking_budget,
                behavior_thinking_default: b_thinking_default,
                behavior_fp8_kv_calibration_tokens: b_fp8_kv_cal,
                behavior_default_kv_dtype: b_default_kv_dtype,
                behavior_default_num_drafts: b_default_num_drafts,
                behavior_disable_tool_steering: b_disable_tool_steering,
                behavior_tool_call_parser: b_tool_call_parser,
                behavior_enable_loop_watchdog: b_enable_loop_watchdog,
                // PR #74 fields — wired from ParsedBehavior.
                behavior_think_loop_min_repeats: pb.think_loop_min_repeats,
                behavior_think_loop_scan_window: pb.think_loop_scan_window,
                behavior_confidence_early_stop: pb.confidence_early_stop,
                behavior_confidence_run_length: pb.confidence_run_length,
                behavior_fuzzy_repeat_tolerance_div: pb.fuzzy_repeat_tolerance_div,
                behavior_max_inter_tool_prose: pb.max_inter_tool_prose,
                behavior_tscg: pb.tscg,
                behavior_disable_tool_grammar: pb.disable_tool_grammar,
                behavior_rollback_resteer: pb.rollback_resteer,
                behavior_rom_head: pb.rom_head.clone(),
                model_type_matches,
                dflash,
            });
        }
    }

    // Sort by (model, quant) for deterministic ordering
    targets.sort_by(|a, b| (&a.model, &a.quant).cmp(&(&b.model, &b.quant)));
    targets
}

/// List subdirectory names (not files) in a directory, sorted.
fn list_subdirs(dir: &std::path::Path) -> Vec<String> {
    let mut dirs: Vec<String> = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("{}: {e}", dir.display()))
        .filter_map(|entry| {
            let entry = entry.ok()?;
            if entry.file_type().ok()?.is_dir() {
                Some(entry.file_name().to_string_lossy().to_string())
            } else {
                None
            }
        })
        .collect();
    dirs.sort();
    dirs
}

#[path = "build_parse.rs"]
mod build_parse;
use build_parse::{
    parse_behavior, parse_dflash, parse_kernel_toml, parse_model_types, parse_sampling_presets,
};

/// Collect .cu files with shadowing across three priority layers:
///   1. shared   — `kernels/$hw/common/` — quant-independent (lowest priority)
///   2. common   — `kernels/$hw/$quant/` — quant-specific shared (medium)
///   3. model    — `kernels/$hw/$model/$quant/` — model-specific (highest, overrides)
///
/// Upstream PR #74 introduces the `kernels/$hw/common/` shared layer for
/// kernels that work across any (model, quant) combination (multi-seq SSM,
/// tree-aware kv scatter, paged-decode kgamma). We adopt the same layout so
/// future merges don't conflict on file locations.
fn collect_cu_files(
    common_dir: Option<&std::path::Path>,
    model_dir: &std::path::Path,
) -> Vec<PathBuf> {
    // Derive the shared dir from common_dir's parent (so we get
    // `kernels/$hw/common/` when common is `kernels/$hw/$quant/`).
    let shared_dir = common_dir.and_then(|c| c.parent().map(|p| p.join("common")));

    let mut files: HashMap<String, PathBuf> = HashMap::new();

    // Layer 1: shared (quant-independent) kernels
    if let Some(ref shared) = shared_dir {
        if shared.is_dir() {
            for f in find_cu_files(shared) {
                let stem = f.file_stem().unwrap().to_str().unwrap().to_string();
                files.insert(stem, f);
            }
        }
    }

    // Layer 2: quant-specific common kernels
    if let Some(common) = common_dir {
        for f in find_cu_files(common) {
            let stem = f.file_stem().unwrap().to_str().unwrap().to_string();
            files.insert(stem, f);
        }
    }

    // Layer 3: model-specific overrides
    for f in find_cu_files(model_dir) {
        let stem = f.file_stem().unwrap().to_str().unwrap().to_string();
        files.insert(stem, f);
    }

    let mut result: Vec<PathBuf> = files.into_values().collect();
    result.sort();
    result
}

/// Find all .cu files in a directory. Returns empty vec if dir doesn't exist.
fn find_cu_files(kernel_dir: &std::path::Path) -> Vec<PathBuf> {
    let Ok(entries) = std::fs::read_dir(kernel_dir) else {
        return Vec::new();
    };
    entries
        .filter_map(|entry| {
            let path = entry.ok()?.path();
            if path.extension().and_then(|e| e.to_str()) == Some("cu") {
                Some(path)
            } else {
                None
            }
        })
        .collect()
}

/// Latest mtime over all `.cuh` files (headers only) in a directory.
/// Used by the PTX-cache freshness check as the conservative shared
/// dependency: any header touch invalidates every `.cu` that could
/// have included it. We don't parse `#include`s, so this is
/// per-target-coarse but per-`.cu`-fine — touching a single `.cu`
/// only re-compiles that one file.
fn latest_header_mtime(dir: &std::path::Path) -> Option<std::time::SystemTime> {
    let entries = std::fs::read_dir(dir).ok()?;
    let mut latest: Option<std::time::SystemTime> = None;
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("cuh") {
            continue;
        }
        if let Ok(mt) = entry.metadata().and_then(|m| m.modified()) {
            latest = Some(latest.map_or(mt, |prev| prev.max(mt)));
        }
    }
    latest
}

/// Combined header-mtime for a target — model dir + common dir + the
/// target-identity signature file. Per-`.cu` cache decisions then take
/// `max(this_cu_mtime, this_target_header_floor)`.
///
/// The signature file lets us invalidate cached PTX when the
/// `(hw, model, quant)` tuple at this `idx` slot changes from a prior
/// build (e.g. user toggled `ATLAS_TARGET_MODEL` between a wildcard
/// and a single model — same `t{idx}__` prefix would otherwise
/// collide with stale PTX).
fn target_header_floor(
    model_dir: &std::path::Path,
    common_dir: Option<&std::path::Path>,
    signature_file: &std::path::Path,
) -> Option<std::time::SystemTime> {
    let mut latest = latest_header_mtime(model_dir);
    if let Some(c) = common_dir {
        if let Some(t) = latest_header_mtime(c) {
            latest = Some(latest.map_or(t, |p| p.max(t)));
        }
    }
    if let Ok(mt) = std::fs::metadata(signature_file).and_then(|m| m.modified()) {
        latest = Some(latest.map_or(mt, |p| p.max(mt)));
    }
    latest
}

#[path = "build_codegen.rs"]
mod build_codegen;
use build_codegen::generate_target_ptx_rs;

#[path = "build_target.rs"]
mod build_target;
use build_target::resolve_compute_target;
// Force recompilation 1775404930
